# https://docs.travis-ci.com/user/multi-os/
os:
  - linux
  # no osx for now (travis build server doesn't work build it)
  # - osx
matrix:
  allow_failures:
    - os: osx
language: python
sudo: required
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
  - "pypy"
before_install:
  # install collective.checkdocs to allow for python setup.py test command to work
  - pip install collective.checkdocs
  # commands for linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gdb          ; fi
  # commands for osx
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/dupes/gdb; fi
script:
  # run unit tests
  - python setup.py test

  # ensure README.rst has no syntax errors so it displays nicely
  # on the pypi website
  - python setup.py checkdocs
cache: pip
