# https://docs.travis-ci.com/user/multi-os/
os:
  - linux
  # no osx for now (travis build server doesn't work build it)
  # - osx
cache:
  pip: true
  yarn: true
  directories:
    - node_modules
language: python
sudo: required
matrix:
  allow_failures:
    - os: osx
  include:
  - python: '3.6'
    env: NOXSESSION="tests-3.6"
  - python: '3.7'
    env: NOXSESSION="tests-3.7"
    dist: xenial
  - python: '3.7'
    env: NOXSESSION="lint"
    dist: xenial
  - python: '3.7'
    env: NOXSESSION="docs"
    dist: xenial

install:
  # commands for linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gdb          ; fi
  # commands for osx
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/dupes/gdb; fi
  - pip install nox
script:
  - nox --non-interactive --session "$NOXSESSION"
