name: "Build gdbgui executables"

on: [push, pull_request]

jobs:
  ubuntu_executable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox
      - name: Compile linux gdbgui executable
        run: |
          nox --non-interactive --session build_executable_linux
      - name: Upload linux executable
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v1
        with:
          name: gdbgui_linux
          path: ./executable/linux

  mac_executable:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox
      - name: Compile mac gdbgui executable
        run: |
          nox --non-interactive --session build_executable_mac
      - name: Upload mac executable
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v1
        with:
          name: gdbgui_mac
          path: ./executable/mac

  windows_executable:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox
      - name: Compile windows gdbgui executable
        run: |
          nox --non-interactive --session build_executable_windows
      - name: Upload windows executable
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v1
        with:
          name: gdbgui_windows
          path: ./executable/windows
